apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: frontend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
