apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: client
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saideep2000/e-commerce-store-front
    targetRevision: HEAD
    path: helm/client
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
