apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saideep2000/e-commerce-store-front.git
    targetRevision: main
    path: helm/server
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true