name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build server application
        run: |
          cd server
          ./mvnw clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push server image
        run: |
          cd server
          docker build -t ecommerce-api:latest .
          IMAGE_ID=$(docker images -q ecommerce-api:latest)
          echo "Using Docker username starting with: ${{secrets.DOCKER_USERNAME}}..."

          docker tag $IMAGE_ID ${{ secrets.DOCKER_USERNAME }}/ecommerce-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-api:latest

      - name: Build and push client image
        run: |
          cd client
          docker build -t ecommerce-ui:latest .
          IMAGE_ID=$(docker images -q ecommerce-ui:latest)
          docker tag $IMAGE_ID ${{ secrets.DOCKER_USERNAME }}/ecommerce-ui:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-ui:latest